add moderator collection moderation endpoints
CenterForOpenScience/osf.io pull request #10097
Opened 2022-11-02 12:58 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

2022-11-07 14:15 UTC, Johnetordoff commented on osf_tests/test_schema_responses.py
> -def _ensure_subscriptions(provider):
Just moving this to a shared folder, not just for schema responses.

2022-11-07 14:16 UTC, Johnetordoff commented on api_tests/providers/collections/views/test_collections_provider_moderator_list.py
> +import mock
This is mostly copied form other provider moderator tests with a few updates.

2022-11-17 20:40 UTC, jwalz requested changes
Gonna be some conflicts to clean up between this and the other CollectionSubmissionAction PRs, but looks mostly good. Just a couple weird things with CoreScopes

2022-11-17 20:40 UTC, jwalz commented on api_tests/providers/collections/views/test_collections_provider_moderator_list.py
> +    def test_GET_unauthorized(self, app, url, provider):
nit: technically unauthenticated, not unauthorized

2022-11-17 20:40 UTC, jwalz commented on framework/auth/oauth_scopes.py
> +    ORGANIZER_WRITE = ORGANIZER_READ + (CoreScopes.ORGANIZER_COLLECTIONS_BASE_WRITE, CoreScopes.NODE_LINKS_WRITE, CoreScopes.WRITE_COLLECTION_SUBMISSION)
If this is a replacement for `COLLECTED_META_READ`, make sure you fix existing API Endpoints

2022-11-17 20:40 UTC, jwalz commented on framework/auth/oauth_scopes.py
> +    WRITE_COLLECTION_SUBMISSION_ACTION = 'write_collection_submission_action'
I don't think we need these. We use `[READ/WRITE]_SCHEMA_RESPONSE` as our scope for `SchemaResponseActionList`, for example.

2022-11-17 20:40 UTC, jwalz commented on api/providers/serializers.py
> +    provider = RegistrationProviderRelationshipField(
(whoops, never submitted this review from last week)

2022-11-29 21:31 UTC, merged