[ENG-4959] Classify notable domains as unverified
CenterForOpenScience/osf.io pull request #10501
Opened 2023-12-11 17:15 UTC by Johnetordoff

## Purpose

Create a new varity of NotableDomain Note for timedout domains.

## Changes

- changes for domain extractor task
- changes to tests.

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/ENG-4959

2023-12-12 13:27 UTC, Johnetordoff commented on osf_tests/test_notable_domains.py
> -        assert domains == {sample_text}
This is the changed test case, others are just changed to pass the note.

2023-12-12 18:32 UTC, mfraezz requested changes
A couple small questions/concerns, but once those are resolved this should be RTM :octocat:

2023-12-12 18:32 UTC, mfraezz commented on osf/models/notable_domain.py
> +        UNVERIFIED = 4  # Timedout couldn't determine
Did you run `python3 manage.py makemigrations`? I would expect a schema change in `note.choices` to generate an automigration, even if it's a functional no-op for the database.

2023-12-12 18:42 UTC, Johnetordoff commented on osf/external/spam/tasks.py
> +        )
@jwalz can you confirm the `is_triaged` behavior here, I'm not sure the admin workflow ramifications.

2023-12-12 21:01 UTC, jwalz commented on osf/external/spam/tasks.py
> +        )
I legit cannot figure out what `is_triaged` is for, but Matt's suggestion seems right

2023-12-15 19:53 UTC, mfraezz commented
Squashed into af35c28a493c29161424fc4f9c7df9d662c0e3c1, consider this merged

2023-12-15 19:53 UTC, closed without merging