ENG-4839 Add advertiseOnDiscoverPage Flag to Provider Model and Admin Interface
CenterForOpenScience/osf.io pull request #10608
Opened 2024-05-07 15:17 UTC by uditijmehta

## Purpose

Adding a boolean attribute to the AbstractProvider model. This change enables administrators to control whether a provider is displayed on the OSF Discover pages directly from the admin interface.

## Changes

- Added advertiseOnDiscoverPage boolean field to AbstractProvider
- Updated the admin forms and templates to include a checkbox for advertiseOnDiscoverPage
- Adjusted the PreprintProviderDisplay view to serialize the new advertiseOnDiscoverPage field

## QA Notes

## Ticket

<https://openscience.atlassian.net/browse/ENG-4839>

2024-05-07 15:30 UTC, Johnetordoff commented
Seems like you should also include a migration file, one created by running `python3 manage.py makemigrations`.

2024-05-07 15:33 UTC, Johnetordoff commented on osf/models/provider.py
> +    advertiseOnDiscoverPage = models.BooleanField(default=True, help_text="Indicates if the provider should be advertised on the discovery page.")
Use underscores and no caps for `advertiseOnDiscoverPage` here please, it's ok in the HTML, but not on the backend. It should follow the convention of the other attribute names.

2024-05-08 13:49 UTC, brianjgeiger requested changes
Almost there. You still need to serialize the field in the API.

2024-05-08 13:49 UTC, brianjgeiger commented on api/providers/serializers.py
> +        'advertise_on_discover_page',
You've made this filterable, which is good, but you still have to add the field to the serializer to get it serialized in the API response. Somewhere around L213 below.

2024-05-08 13:58 UTC, brianjgeiger commented
Also it looks like you have too many blank lines, according to Flake8:

```
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing admin/preprint_providers/views.py

Flake8...................................................................Failed
hookid: flake8

admin/preprint_providers/forms.py:33:5: E303 too many blank lines (2)
```

2024-05-08 15:37 UTC, brianjgeiger commented on osf/migrations/0020_auto_20240508_1455.py
> +    ]
I think you need to delete this migration.

2024-05-08 19:16 UTC, brianjgeiger approved these changes

2024-05-09 18:08 UTC, merged