[WIP]Feature/develop updates
CenterForOpenScience/osf.io pull request #10618
Opened 2024-05-15 15:46 UTC by opaduchak

## Purpose

## Changes

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

2024-05-19 21:50 UTC, cslzchen requested changes
Looks great and 💯 for handling the merge conflicts. A few requests before I am back on Tuesday, thanks!

- [x] Fix trivial import style in `addons/base/views.py`
- [x] Update PR title (ticket number, no longer WIP, etc.)
- [ ]  Add a little bit details to the PR description, this doesn't have to be long, what  @ly-mariia mentioned in Slack to me is good enough
- [ ]  Can any of you verify **locally** that "after this PR is merged in to the feature branch, there is no conflicts merging the feature branch back to the `develop`"?

On question, related to the last item above, I think this https://github.com/CenterForOpenScience/osf.io/commit/35d5512477e02f9d01db2e744c7c41778d42c67b is the actual `merging develop into feature branch` commit that includes conflict fixing. If so, (a note for myself) I will rename it to Merge `develop` into `feature/python-upgrade` and fix conflicts.

Another note for myself: back-up the feature branch before merge, create a dedicated phase 3 branch for deployment after merge.

2024-05-19 21:50 UTC, cslzchen commented on addons/base/views.py
> +from osf.utils.requests import requests_retry_session
Can we move this import to after `from osf.utils import permissions` in line 59?

2024-05-20 10:48 UTC, opaduchak commented
> On question, related to the last item above, I think this [35d5512](https://github.com/CenterForOpenScience/osf.io/commit/35d5512477e02f9d01db2e744c7c41778d42c67b) is the actual `merging develop into feature branch` commit that includes conflict fixing. If so, (a note for myself) I will rename it to Merge `develop` into `feature/python-upgrade` and fix conflicts.
Indeed, it is.
And regarding local check, I doubt that this is necessary, because this commit already resolved all conflicts. (I compared develop and this branch on github, and there aren't any conflicts)

2024-05-21 13:11 UTC, cslzchen approved these changes

2024-05-21 13:44 UTC, cslzchen commented
Cc @felliott, due to conflicts fix (https://github.com/CenterForOpenScience/osf.io/pull/10618/commits/35d5512477e02f9d01db2e744c7c41778d42c67b) when merging `develop` into the feature branch, `rebase`, `merge --no-ff` and pushing back couldn't work. Now merging this PR in GitHub directly.

2024-05-21 13:45 UTC, merged