[ENG-5762] Get GV set up in osf docker configs
CenterForOpenScience/osf.io pull request #10643
Opened 2024-06-19 09:13 UTC by opaduchak

## Purpose
The purpose of this pr is to integrate gravyvalet into osf's docker-compose.yml for more straightforward development experience

## Changes

- Added `gv` and `gv-requirements` services to `docker-compose.yml`
- Added `.docker-compose.gv.env` file for gravyvalet environment definition

## QA Notes

It'd be great for other folks to try it out before merge, to mitigate "works on my machine" type of risks 

## Documentation

## Side Effects

## Ticket
[ENG-5762](https://openscience.atlassian.net/browse/ENG-5762)

2024-06-21 19:09 UTC, aaxelb requested changes
good start! could you also update `README-docker-compose.md` to match? might be as simple as adding `gv` next to `wb` and `gv_requirements` next to `wb_requirements`, but i forget what all is in there

2024-06-24 11:38 UTC, opaduchak commented on .docker-compose.gv.env
> +POSTGRES_DB="gravyvalet"
added postgres SQL init script to create `gravyvalet` db if not exists

2024-06-24 13:38 UTC, aaxelb approved these changes
only a docs nit, otherwise looks good (TIL psql's `\gexec` -- little indirect but works for me)

2024-06-24 13:38 UTC, aaxelb commented on README-docker-compose.md
> +  - After creating migrations, resetting your database, or starting on a fresh install you will need to run migrations to make the needed changes to database. This command looks at the migrations on
nit: this line is duplicated (tho i agree it makes more sense after the `migrate` commands

2024-06-24 13:55 UTC, aaxelb approved these changes
🦑

2024-06-28 15:12 UTC, merged