[ENG-3685] Add permissions for withdrawn registration files
CenterForOpenScience/osf.io pull request #10650
Opened 2024-06-25 20:55 UTC by uditijmehta

## Purpose

Implement custom permissions to handle file access for withdrawn registrations.

## Changes

Added WithdrawnRegistrationPermission and updated FileDetailPermission to enforce access control for withdrawn registrations.

## Ticket

<(https://openscience.atlassian.net/browse/ENG-3685)>

2024-06-26 17:10 UTC, brianjgeiger requested changes
One minor thing, plus it might be nice if you could add in a couple of tests for this.

2024-06-26 17:10 UTC, brianjgeiger commented on api/files/permissions.py
> +class FileDetailPermission(WithdrawnRegistrationPermission, permissions.BasePermission):
Under what circumstances might the WithdrawnRegistrationPermission be used on something that's not a File? It seems pretty file specific. We could probably just combine these two classes into one `RegistrationFileDetailPermission` instead.

2024-06-26 20:15 UTC, jwalz commented
So, I looked into this a while ago, and I think the actual easiest thing to do is to add a check for `target.is_retracted` the same way we do for `target.deleted` here (or, technically, `getattr(target, 'is_retracted', False)`): https://github.com/CenterForOpenScience/osf.io/blob/develop/api/files/views.py#L53

I don't love mixing permissions in with the `get_queryset` functionality, but a) we already do it and b) it feels significantly more appropriate for something that we want to universally mark `GONE` than for actual permissions.

Also, want to update `get_auth` [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/addons/base/views.py#L305) to make sure that WB download links also break (since retractions are always visible)

2024-06-28 12:36 UTC, brianjgeiger approved these changes

2024-07-03 13:47 UTC, jwalz commented on api/files/permissions.py
> +class RegistrationFileDetailPermission(permissions.BasePermission):
So, I don't think this is actually necessary with the change to `get_file`. Sorry for the misleading ticket. I meant to update it after my explorations a couple weeks ago but didn't notice that this ticket actually got scheduled. >_<

Should be sufficient to just comment out the inclusion of this permission and re-run tests locally to see if that's right.

2024-07-03 13:47 UTC, jwalz commented on api/files/serializers.py
> +        if isinstance(value.target, Registration) and value.target.is_retracted:
Is this actually reachable? Shouldn't the view 410 before any data hits the serializer?

2024-07-03 13:47 UTC, jwalz commented on api_tests/files/views/test_file_detail.py
> +        resource.save()
fun fact, we have an internal shorthand for this:
`retraction.accept()` with no Auth will skip the required approval steps.

2024-07-03 13:47 UTC, jwalz commented on api/files/views.py
> +        RegistrationFileDetailPermission,
If the permission class *is* needed, then it's a pure replacement for the `PermissionWithGetter(...)` above, and that line can be removed.

2024-07-05 17:14 UTC, jwalz approved these changes

2024-07-09 18:51 UTC, merged