[ENG-5966] 2.0.1 BE: Update permission to support edit as a WRITE contributor
CenterForOpenScience/osf.io pull request #10687
Opened 2024-07-25 15:47 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/ENG-5966

2024-07-29 14:34 UTC, Johnetordoff commented on api_tests/preprints/views/test_preprint_institutions_relationship.py
> -        preprint.add_permission(user, 'admin')
This lead to an odd bug in our permissions.

2024-08-13 19:53 UTC, cslzchen requested changes
Looks good overall and love the unit tests 👍 . In addition to my comments,

- [x] First, how about changing `test_author_assertions_preprint_detail.py` to `test_preprint_detail_author_assertions_.py`?
- [ ] Have you check the withdrawal logic? I think we are fine since that piece is probably separate piece from the detail serializer.

2024-08-13 19:53 UTC, cslzchen commented on api_tests/preprints/views/test_preprint_institutions_relationship.py
> +        return user
For all the fixtures, if not too much effort, can we add more than one affiliation to the user to test more variations. e.g.

* Admin has A, B, C
* Write has B, C, D
* Read has C, E, F

2024-08-13 20:04 UTC, Johnetordoff commented on api_tests/preprints/views/test_author_assertions_preprint_detail.py
> +        preprint.add_contributor(user, READ)
It's to check that being the creator alone shouldn't be enough to change the author assertions, only any admin. I thought it was good to include. I vaguely remember you telling me to test for this, but I can't remember when or why.

2024-08-14 15:17 UTC, cslzchen approved these changes

2024-08-14 15:19 UTC, cslzchen commented on api_tests/preprints/views/test_author_assertions_preprint_detail.py
> +        preprint.add_contributor(user, READ)
Ah, I vaguely remember this too and yeah, make sense.

2024-08-14 17:46 UTC, merged