[ENG-4438] Add OOPSpam and Akismet metrics to spam report
CenterForOpenScience/osf.io pull request #10783
Opened 2024-10-21 14:03 UTC by uditijmehta

## Purpose

Add OOPSpam and Akismet metrics to track flagged and hammed content

## Changes

- SpamCountReporter: Added OOPSpam and Akismet spam/ham metrics for nodes, registrations, preprints, and users.
- SpamSummaryReport: Added new fields for OOPSpam and Akismet flagged/hammed counts.
- OOPSpamClient & AkismetClient: Added methods to get flagged and hammed content counts.

## Ticket

(https://openscience.atlassian.net/browse/ENG-4438)

2024-10-24 15:44 UTC, mfraezz requested changes
Quick Drive-By CR. One functional issue that needs fixing in a couple places, and some smaller things preventing the build from passing.

Please also add a Deployment Note in the PR description that, because the metric report is changing, `sync_metrics` will need to be ran

2024-10-31 16:43 UTC, mfraezz reviewed
The code/tests itself LGTM, however in reviewing the ticket and considering the request, two relevant considerations came up:

1) Description, comments on this ticket indicate that it should be in a _private_ metrics Report, but it isn't clear whether this information should be in a new private Report, or if it should be added to the SpamCountReporter (as it currently is) and that report should be made private.
Recommendation: seek clarity from Product regarding this. In either case, some additional work will be required
2) The spirit of this request is in seeking clarity on true-vs-false positive rates of automatic spam classification, however this PR only address Nodes. Preprints are another, perhaps larger category of spam, and we may want to extend this functionality to Preprints as well. 
Recommendation: Confirm if that is desired by Product, and if so add a `category` param to the `get_*_count` fn's to keep things DRY, and conditionally use `PreprintLog`, `preprint__spam_data__<etc>` instead. Extend report, tests as appropriate.

Pass complete :octocat:

2024-11-05 15:06 UTC, uditijmehta commented
@mfraezz I checked in with Product, and based on that, I made the updates—set up a new private metrics report, included preprints, and added the category parameter.

2024-11-05 17:37 UTC, mfraezz requested changes
Aside from one minor comment, code here looks good. 🍔 

However, in order for the new report to run on the monthly cadence, it will also need to be added to the `AllMonthlyReporters` `Enum` in `osf/metrics/reporters/__init__`

Should be ready to merge after that. Pass complete :octocat: 

There may be a follow-up ticket created to make this new report available, with adequate permissions restrictions, in the metrics API. However, I expect that to be enough work to merit its own ticket, so can be deferred for now.

2024-11-05 17:37 UTC, mfraezz commented on osf/external/askismet/client.py
> +        log_model = NodeLog if category == 'node' else PreprintLog
Minor: it would be preferable if an error was raised if `category` wasn't in an controlled list of terms (e.g. `['node', 'preprint']`)

2024-11-05 19:59 UTC, mfraezz approved these changes

2024-11-05 19:59 UTC, merged