[WIP][ENG-6668] Add Contributor Page Improvements for Institutional Access
CenterForOpenScience/osf.io pull request #10825
Opened 2024-12-05 13:34 UTC by Johnetordoff

## Purpose

The new Institutional Access feature creates a new "Curator" role that has certain requirements. The first is that it have a special label in the contributor list, shown here: 
![Screenshot 2024-12-05 at 8 30 26 AM](https://github.com/user-attachments/assets/2f42e49e-bbab-483c-b303-6ed139c9639f)

The second requirement is that the user is unable to set the curator to a bibliographic or "visible contributor.

## Changes

- Add check constraint to avoid visible institutional admins.
- Locates area in page where Curator status can be lableled
- adds tests to test for specific behavior at model and API level

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/ENG-6668

2025-01-03 16:32 UTC, Johnetordoff commented on website/project/views/contributor.py
> +    except IntegrityError as error:
This shouldn't be hittable because the checkbox is disabled, but sends right message just in case.

2025-01-09 21:09 UTC, brianjgeiger requested changes
A few comments and questions.

2025-01-09 21:09 UTC, brianjgeiger commented on osf/models/contributor.py
> +            return super().save(*args, **kwargs)
I think this could be simplified by saying `if self.user.is_institutional_admin_or_curator() and self.visible`, then just elsing the super call.

2025-01-09 21:09 UTC, brianjgeiger commented on osf_tests/test_institutional_admin_contributors.py
> +    def test_contributor_with_visible_and_institutional_admin_raises_error(self, institutional_admin, project, institution):
Are you testing the positive cases elsewhere? That you can set other fields on a curator's contributor object successfully?

2025-01-09 21:09 UTC, brianjgeiger commented on website/static/js/accessRequestManager.js
> +    self.visible = ko.observable(!accessRequest.user.is_curator);
Could we make this visible but disabled to match with the other checkboxes in this control?

2025-01-09 21:09 UTC, brianjgeiger commented on osf/models/user.py
> +    def is_institutional_admin_or_curator(self, institution=None, node=None):
This seems like two separate functions: `is_institutional_admin` and `is_curator`. Should it be?

2025-01-09 21:16 UTC, Johnetordoff commented on osf/models/user.py
> +    def is_institutional_admin_or_curator(self, institution=None, node=None):
My feeling is the word curator only applies when you actually have a node, so all curator are insti admins which makes lumping these together somewhat justifiable, but your right it's unclear. Let me address the other things and come back to this.

2025-01-09 21:20 UTC, Johnetordoff commented on website/static/js/accessRequestManager.js
> +    self.visible = ko.observable(!accessRequest.user.is_curator);
You misunderstand, `self` is the user, not the HTML element, and visible refers to the user's bibliographic status. This doesn't effect the visibility of the checkboxes, it ensures all curators default to non-visible/bibliographic status.

2025-01-09 21:43 UTC, brianjgeiger commented on website/static/js/accessRequestManager.js
> +    self.visible = ko.observable(!accessRequest.user.is_curator);
Gotcha. Pretend like this comment was down below in the mako file then.

2025-01-09 21:52 UTC, Johnetordoff commented on website/static/js/accessRequestManager.js
> +    self.visible = ko.observable(!accessRequest.user.is_curator);
Yes I see that's a better visual user-facing move. I don't think Product will mind this slight deviation.

2025-01-10 14:22 UTC, Johnetordoff commented on osf/models/user.py
> +    def is_institutional_admin_or_curator(self, institution=None, node=None):
I split the method up into three separate ones, that looks much better thank you.

2025-01-10 16:14 UTC, brianjgeiger requested changes
One tiny thing, and then one more check to see if we're using the right information for making UI decisions.

2025-01-10 16:14 UTC, brianjgeiger commented on website/profile/utils.py
> +        'is_institutional_admin': user.is_institutional_admin(),
Do we need this for this view? It looks like it's being used, but is it being used properly? See below for more.

2025-01-10 16:14 UTC, brianjgeiger commented on website/project/views/contributor.py
> +            'You can not make an institutional admin a bibliographic contributor.',
```suggestion
            'You can not make an institutional curator a bibliographic contributor.',
```

2025-01-10 16:14 UTC, brianjgeiger commented on website/templates/project/contributors.mako
> +            <div data-bind="ifnot: accessRequest.user.is_institutional_admin">
Is this correct, or is it that the request was made from the institutional dashboard? Does the request need to store this info, rather than inferring it from the institutional admin status? This goes back to not wanting all institutional admins to be automatically classified as a curator request.

2025-01-10 16:34 UTC, Johnetordoff commented on website/templates/project/contributors.mako
> +            <div data-bind="ifnot: accessRequest.user.is_institutional_admin">
Yes you are correct, I checked with Product again and they confirmed. This should ensure the user actually has made a pending institutional access request, not a normal access request.

2025-01-10 18:12 UTC, brianjgeiger requested changes
Almost there. One optimization left.

2025-01-10 18:12 UTC, brianjgeiger commented on osf/models/user.py
> +        ).exists()
Just to be sure, is there any place we can cache this info, such as a request object, rather than relying on this query, the same way we did with caching on the contributor object if it's a curator? Same reason as before, to avoid making this query for every contributor that gets serialized.

2025-01-10 18:12 UTC, brianjgeiger commented on website/templates/project/contributors.mako
> +            <div data-bind="ifnot: accessRequest.user.has_institutional_request">
So here, for example, could be `accessRequest.is_curator` or similar.

2025-01-10 18:37 UTC, brianjgeiger requested changes
Still a bit more. What you did was not what I was asking for.

2025-01-10 18:37 UTC, brianjgeiger commented on osf/models/contributor.py
> +        return self.user.has_institutional_request(self.node)
This is still going to make the query once per contributor when loading the page. Could we make a boolean field on the `NodeRequest` (or maybe `AbstractRequest`, if we want to plan for the future) model to hold this information?

2025-01-10 20:49 UTC, brianjgeiger approved these changes
🎉 🐧 🎉

2025-01-10 21:17 UTC, brianjgeiger commented
Well, except for the failing tests.

2025-01-13 13:51 UTC, merged