[ENG-6693] Add new tests for preprint moderation states
CenterForOpenScience/osf.io pull request #10869
Opened 2024-12-20 16:33 UTC by Vlad0n20

## Purpose

Add new tests for preprint moderation states
## Changes
## QA Notes

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/ENG-6693?atlOrigin=eyJpIjoiOTBhN2U1MTg5M2U0NGI1YjgxNGRkZTYwYTUzYTMxOWYiLCJwIjoiaiJ9

2024-12-23 09:23 UTC, Ostap-Zherebetskyi commented
Overall looks good, the only suggestion is to add more checks for the “submit” and “accept” tests

An example of a test flow:
1. Create a preprint 
2. submit/accept
3. Check guid.referent, is_published, etc.
4. Create a second version 
5. submit/accept
6. Check guid.referent, is_published, etc. for the second version

2024-12-24 03:56 UTC, cslzchen requested changes
First, why put these tests in class `TestWithdrawnPreprint`? Please check if there are existing pre/post moderation tests. If exists, then we can expand them to check new version (i.e. no need to check first version). If not, we need to create a new class testing both initial version and new versions.

Second, I think there are a lot of cases to cover (if not covered by existing tests). Here is a few I have in mind. Please note the withdraw piece can be included in `TestWithdrawnPreprint`.

* Pre-moderation
  * Initial submission (pending, unpublished)
    * Accept
    * Reject
    * Withdraw when pending
    * Withdraw after accepted
  * New version creation (pending, unpublished)
    * Accept
    * Reject
    * Withdraw after accepted
 
* Post-moderation
  * Initial submission (pending, published)
    * Accept
    * Withdraw
  * New version creation
    * Accept
    * Withdraw

* No-moderation: we should test this one as well since "no-moderation" exists locally, on staging/test servers (though not on production server).
  * Initial submission
    * Withdraw
  * New version submission
    * Withdraw

* Hybrid-moderation
  * Preprints doesn't have hybrid moderation, no need to test

Hope this rough guide helps.

2024-12-30 17:45 UTC, cslzchen approved these changes
Looks awesome, I will merge after I have finished all my selenium stuff on staging2.

2024-12-31 23:05 UTC, cslzchen approved these changes
Reworked preprint and version moderation tests

2025-01-01 14:09 UTC, merged