Changes for "can_request_access" feature
CenterForOpenScience/osf.io pull request #10877
Opened 2024-12-30 10:34 UTC by bodintsov

## Purpose

Add to admin "can_request_access" option to the institution
API Changes for "can_request_access" feature

Done 2 tasks (ENG-6779) and (ENG-6780) within one PR, due to tickets being related to each other

## Changes

TBD

## QA Notes

TBD

## Documentation

TBD

## Side Effects

TBD

## Ticket

(https://openscience.atlassian.net/browse/ENG-6779)
(https://openscience.atlassian.net/browse/ENG-6780)

2024-12-30 14:48 UTC, brianjgeiger requested changes
The changes so far look good with one small change, but we're missing the admin app functionality.

2024-12-30 14:48 UTC, brianjgeiger commented on osf/models/institution.py
> +    can_request_access = models.BooleanField(default=False, db_index=True)
I don't think we need to index this field. I don't know of any use cases right now where we'd be filtering on can_request_access.

2024-12-30 14:48 UTC, brianjgeiger commented
Oh, and also tests need to be fixed.

2024-12-30 14:59 UTC, brianjgeiger commented
While you're in there fixing tests, you might as well add some new ones to cover the new field.

2024-12-30 16:03 UTC, bodintsov commented
> The changes so far look good with one small change, but we're missing the admin app functionality.

@brianjgeiger On the OSFadmin app, on the page of an institution, there is a possibility to change the `can_request_access` field. Maybe I missed something, and it needs to be done elsewhere?

2024-12-30 16:21 UTC, brianjgeiger commented
> On the OSFadmin app, on the page of an institution, there is a possibility to change the can_request_access field.

Oh, very good. Could take a screenshot and put it in the PR description, please?

2024-12-30 21:58 UTC, bodintsov commented
> Oh, very good. Could take a screenshot and put it in the PR description, please?

Yes sure, I added a screenshot

2025-01-02 02:17 UTC, brianjgeiger commented
@bodintsov Looks like tests are still failing.

2025-01-02 15:53 UTC, brianjgeiger reviewed
Just a couple of questions about an unexpected set of changes.

2025-01-02 15:53 UTC, brianjgeiger commented on framework/email/tasks.py
> +        to_emails=to_addr,
Was this to fix a test?

2025-01-02 15:53 UTC, brianjgeiger commented on framework/email/tasks.py
> +        mail.category = [Category(x) for x in categories]
Same here, why the change?

2025-01-03 14:22 UTC, Johnetordoff commented
@brianjgeiger @bodintsov is having some failing tests due to my changing of the sendgrid method, heres the fails on the feature branch https://github.com/CenterForOpenScience/osf.io/actions/runs/12380790854/job/34557929049?pr=10884. I told him to adjust the tests because that is working on staging.

2025-01-04 09:08 UTC, bodintsov commented
I can`t fix tests because the `add_category` method does not work. It is not assigning categories to the Mail object. Without fixing `_send_with_sendgrid` it is impossible to set proper tests.

2025-01-06 13:42 UTC, brianjgeiger commented
@bodintsov Okay, understood. This overall looks good, but I see some likely unrelated test failures that will need to be handled one way or another before this can be merged. I'm checking with another team on Slack to see if this is related to their work, and we'll figure out where to go from here when they respond.

2025-01-07 14:12 UTC, brianjgeiger commented
@bodintsov Okay, since you're fixing the broken tests in another PR, and we've already merged things that have those broken tests in, I will approve this once the merge conflicts are fixed, then let @Johnetordoff do a pass.

2025-01-07 20:51 UTC, Johnetordoff requested changes
You got the goal of the assignment correct, but there's some changes that are necessary before merging. If you have some more questions ping me on Slack, if something seems odd or too difficult, it's probably just a misunderstanding. Good first draft. Thanks!

2025-01-07 20:51 UTC, Johnetordoff commented on api/institutions/serializers.py
> +    can_request_access = ser.CharField(read_only=True)
Make it clear this refers to a specific feature. Refactor to something like `institutional_request_access_enabled`

2025-01-07 20:51 UTC, Johnetordoff commented on osf/migrations/0026_institution_can_request_access.py
> +# Generated by Django 4.2.15 on 2024-12-27 14:08
Bunch this in with the other migrations on this branch, just to be tidy. Delete both this and 0025 and re-run `makemigrations` and use that file.

2025-01-07 20:51 UTC, Johnetordoff commented on osf_tests/factories.py
> +    can_request_access = False
I would default this to true, just because it's going to true going forward, but I'm not sure if it will break a bunch of tests consider using True here.

2025-01-07 20:51 UTC, Johnetordoff commented on osf_tests/factories.py
> +    def _create(cls, *args, **kwargs):
I don't know what the point of doing this is, write a comment/docstring explaining or remove it.

2025-01-07 20:51 UTC, Johnetordoff commented on tests/framework_tests/test_email.py
> +        # Added this crutch as test fail due to improper work of method `add_category`. This method do not add categories
I think we cleared up all these email tests, seems like you should be able to remove this lines.

2025-01-07 20:51 UTC, Johnetordoff commented on osf/models/user.py
> +        return self.groups.filter(name=group_name).exists() and institution.can_request_access
It's difficult question where this AND check should be in the codebase. The `institutional_admins` permission may have other uses in the future that don't involve this feature, even though this is a quick fix and probably works for now you should move this check to the permissions classes that also check for this feature's request_type. `UserMessagePermissions` and `InstitutionalAdminRequestTypePermission` are better places to insert a conditional for this feature.  `is_institutional_admin` can't "lie" about whether the user has that permission just because the feature is on/off.

2025-01-07 20:51 UTC, Johnetordoff commented on api_tests/users/views/test_user_message_institutional_access.py
> +    def test_institutional_admin_can_not_create_message(self, mock_send_mail, app, institutional_admin_on_institution_without_access,
There should be a test for the request node endpoint too.

2025-01-07 21:04 UTC, brianjgeiger commented on osf_tests/factories.py
> +    can_request_access = False
I would leave this as False, please. We don't want Product to have to turn this off for every institution to start with. We can always change it to True after launch once it goes fully into use.

2025-01-09 18:08 UTC, brianjgeiger approved these changes

2025-01-09 18:35 UTC, Johnetordoff approved these changes

2025-01-09 19:13 UTC, merged