[ENG-1994] fix early embargo termination
CenterForOpenScience/osf.io pull request #9443
Opened 2020-07-23 16:35 UTC by Johnetordoff

## Purpose

Embargoes never go away if the the users request early termination and contributors don't reply until after deadline.

## Changes

- add termination statement for registration approval script

## QA Notes

  - Does this change require a data migration? If so, what data will we migrate?
No
  - What is the level of risk?
Low
    - Any permissions code touched?
No
    - Is this an additive or subtractive change, other?
additive
  - How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?)
by attempting to replicate the bug

## Documentation

🐞 fix, no docs

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-1994

2020-07-31 15:43 UTC, Johnetordoff commented on osf_tests/embargoes/test_embargoes.py
> +        embargo.state = Sanction.APPROVED
Yeah it's confusing, but we are test for the original `approved` embargo and using the periodic check on that orginal approved one to cancel the `unapproved` secondary one when the first expires. You can't technically request `request_embargo_termination` on an `unapproved` embargo, the validation logic forbids it.

2021-05-26 13:16 UTC, jwalz requested changes

2021-05-26 15:56 UTC, jwalz commented on osf_tests/embargoes/test_embargoes.py
> +        assert registration.embargo_termination_approval.state == Sanction.APPROVED
reminder to test the registration's `moderation_state` here.

2021-05-26 15:56 UTC, jwalz commented on osf/models/registrations.py
> +        if self.embargo_termination_approval:
nit: would prefer to check `self.is_pending_embargo_terminaton`. This version will trigger some unnecessary state machine code in the case of an actual EmbargoTerminationApproval.

2021-05-27 21:07 UTC, merged