[ENG-2306][WIP] Four new registration forms
CenterForOpenScience/osf.io pull request #9506
Opened 2020-10-20 19:39 UTC by Johnetordoff

## Purpose

Adds new schemas for OSF preregistration

## Changes

- 4 new schemas and a migrations

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify all language is the same as as the excel spreadsheet
- Verify all schemas are initially invisible

## Documentation

simple tech task, no docs.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-2306

2020-10-22 16:06 UTC, UdayVarkhedkar requested changes
Just needs a few small corrections to bring it in line with the spreadsheets defining the schemas.

2020-10-22 16:06 UTC, UdayVarkhedkar commented on website/project/metadata/real-world-evidence.json
> +               "qid":"q20",
This look like it should be required

2020-10-22 17:24 UTC, UdayVarkhedkar approved these changes

2020-10-22 20:16 UTC, brianjgeiger requested changes
The information I have is wildly different from what I'm seeing here. Am I missing something? If I am, could you point me to the correct information? If I'm not, can you go back through and double-check everything to make sure it's all good?

Also, one of these registrations should not be invisible.

2020-10-22 20:16 UTC, brianjgeiger commented on website/project/metadata/asist-hypothesis-capability-registration.json
> +   "description":"This template was created by researchers from the qualitative community for preregistration of qualitative research",
According to [the ticket](https://openscience.atlassian.net/browse/ENG-2306), this should be, "This preregistration template is part of the DARPA Artificial Social Intelligence for Successful Teams (ASIST) program. This template is intended to formally register performer hypothesis and AI capability preregistrations throughout the ASIST program."

2020-10-22 20:16 UTC, brianjgeiger commented on website/project/metadata/asist-hypothesis-capability-registration.json
> +               "description":"Please specify the overall purposes, objectives or aims of the research.\n\nIn addition, please reflect on whether your aim is different across different domains (e.g. k
Where did this text come from? The spreadsheet I have looks more like this:

<img width="638" alt="Screen Shot 2020-10-22 at 4 03 05 PM" src="https://user-images.githubusercontent.com/6599111/96924584-d95c3400-1480-11eb-9e35-cefc3878d31d.png">

2020-10-22 20:16 UTC, brianjgeiger commented on website/project/metadata/asist-hypothesis-capability-registration.json
> +               "description":"Please upload your pre-analysis plan, along with any other supporting documents, such as survey instrument, research protocol, any data, etc. OSF functionality allows fo
This also does not match with what I see in the spreadsheet.

2020-10-23 18:36 UTC, brianjgeiger requested changes
I did a more thorough pass. Here's everything I could find.

2020-10-23 18:36 UTC, brianjgeiger commented on website/project/metadata/real-world-evidence.json
> +               "description":"Please choose one the population under evaluation in the study",
This was wrong in the spreadsheet. It should be, "The population under evaluation in the study"

2020-10-23 18:36 UTC, brianjgeiger commented on website/project/metadata/real-world-evidence.json
> +               "help":"a prior diagnosis of condition X.",
Capitalize "A"

2020-10-23 18:36 UTC, brianjgeiger commented on website/project/metadata/real-world-evidence.json
> +               "title":"Specific Inclusion criteria",
"Specific Exclusion criteria"

2020-10-23 18:36 UTC, brianjgeiger commented on website/project/metadata/real-world-evidence.json
> +               "description":"TPlease choose the one best short description that best reflects the amount of data handling that you have had up until the date of registration for this study.",
Typo: "Please" not "TPlease"

2020-10-23 19:41 UTC, brianjgeiger commented
Based on the [last travis run](https://travis-ci.org/github/CenterForOpenScience/osf.io/builds/738353570) it looks like this might not be up-to-date with develop and its migrations.

2020-10-25 17:26 UTC, brianjgeiger commented on osf/migrations/0221_add_schemas.py
> +        ('osf', '0218_auto_20200929_1850'),
0219_auto_20201020_1836.py

2020-10-26 12:58 UTC, brianjgeiger commented on osf/migrations/0221_add_schemas.py
> +        ('osf', '0218_auto_20200929_1850'),
```suggestion
        ('osf', '0219_auto_20201020_1836'),
```

2020-10-26 15:22 UTC, brianjgeiger approved these changes

2020-10-26 15:23 UTC, merged