[ENG-2373] Fix Sanction "pending" conditions
CenterForOpenScience/osf.io pull request #9538
Opened 2020-11-16 18:19 UTC by jwalz

## Purpose
Make the `is_pending` property of Sanction objects operate correctly with the old `state` field until the new `sanction_state` field is backfilled.

The default value for the `sanction_state` field is `PENDING_ADMIN_APPROVAL`, which was the condition being checked previously by `is_pending`. That means that all sanctions created before the `sanction_state` field was applied would return True for `is_pending`.

We need to only return True for sanctions in `PENDING_ADMIN_APPROVAL` that ALSO have a `state` value of `UNAPPROVED` to ensure that we don't return false positives for these old entries.

## Changes
* `sanction.is_pending` now checks for `sanction.state == Sanction.UNAPPROVED` as well as `sanction.approval_stage is SanctionSates.PENDING_MODERATOR_APPROVAL`

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket
https://openscience.atlassian.net/browse/ENG-2373

2020-11-16 20:28 UTC, brianjgeiger requested changes
Is there an assert you could throw into a test somewhere to ensure this is returning properly?

2020-11-16 20:38 UTC, jwalz commented
> Is there an assert you could throw into a test somewhere to ensure this is returning properly?

Was letting Travis run while I did other stuffs to make sure I didn't break anything unexpected. Will add an explicit test somewhere.

2020-11-16 20:43 UTC, brianjgeiger commented
Cool cool. I know you didn't put it into review yet, so I was jumping the gun. :)

2020-11-17 18:23 UTC, brianjgeiger approved these changes

2020-11-17 18:23 UTC, merged