[ENG-2398] Make figshare work with new public private rules
CenterForOpenScience/osf.io pull request #9566
Opened 2020-12-04 13:51 UTC by Johnetordoff

## Purpose

Well this was supposed to be an analysis ticket to look at new changes to Figshare's API but seemingly the only change was to a single attribute `date_published` so I decided just to fix that bug.

## Changes

- use the public/user Figshare API endpoint to see if a project is public or not.

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify all figshare functions work as intended.

## Documentation

🐞 fix, no docs.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-2398

2020-12-07 19:10 UTC, corbinSanders commented on addons/figshare/models.py
> +                project_is_public = connect.article_is_public(self.folder_id)
`project_is_public` could not be instantiated.

2020-12-07 19:12 UTC, corbinSanders requested changes
LGTM. One nit

2020-12-07 19:52 UTC, corbinSanders commented
LGTM!

2020-12-09 17:34 UTC, brianjgeiger approved these changes

2023-04-05 20:20 UTC, closed without merging