[ENG-2106] Add management command to copy custom taxonomies to allow hightlighting
CenterForOpenScience/osf.io pull request #9574
Opened 2020-12-08 15:27 UTC by Johnetordoff

## Purpose

To allow providers with the standard bepress taxonomy to highlight certain subjects, we need to copy that providers taxonomy into postgres. This adds a management command to copy over the standard taxonomy.

## Changes

- adds management command that copies taxonomy with tests

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify that "OSF Subjects" in the admin app lists all the subjects for the provider and that highlighted status can be changed.

## Documentation

new management command, no docs.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-2106

2020-12-08 21:35 UTC, UdayVarkhedkar approved these changes
Looks good to me!

2020-12-08 21:38 UTC, UdayVarkhedkar requested changes
Actually, this looks like it doesn't check for if the provider has a custom taxonomy/custom subjects before copying the bepress taxonomy over as the ticket requests. Could you add some type of check for that or comment why it isn't necessary?

2020-12-09 14:09 UTC, UdayVarkhedkar approved these changes

2021-02-05 19:58 UTC, jwalz approved these changes

2021-03-05 01:33 UTC, merged