[warmfix] retracted preprints may actually be spam
CenterForOpenScience/osf.io pull request #9579
Opened 2020-12-09 22:10 UTC by aaxelb

## Purpose
make sure spam preprints don't show up in search results

## Changes
close a loophole wherethrough spam preprints are surfaced in SHARE if
they have ever been retracted.

may apply retroactively by calling `api.share.utils.update_share` on
each of:
```py
Preprint.objects.filter(
    date_withdrawn__isnull=False,
    spam_status__in=[SpamStatus.FLAGGED, SpamStatus.SPAM],  # or whatever is most appropriate
)
```

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify that if a preprint is both retracted/withdrawn AND marked spam, it remains hidden

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

2020-12-11 18:40 UTC, brianjgeiger approved these changes

2020-12-11 18:41 UTC, brianjgeiger requested changes
A test or two might go nicely with this.

2020-12-15 15:24 UTC, mfraezz approved these changes

2020-12-16 16:11 UTC, brianjgeiger approved these changes

2020-12-21 21:56 UTC, mfraezz commented
Cherry-picked in as https://github.com/CenterForOpenScience/osf.io/commit/c29676b672535fe96168dbc05b189a5d2dc625c5, consider this merged ⛏️

2020-12-21 21:56 UTC, closed without merging