[ENG-2107][WIP] Clean up withdrawn preprint and registration files
CenterForOpenScience/osf.io pull request #9593
Opened 2021-01-05 18:44 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/https://openscience.atlassian.net/browse/ENG-2107

2021-01-07 15:32 UTC, Johnetordoff commented on addons/osfstorage/models.py
> +        return super().delete(user=user) if self._check_delete_allowed() else None
This is a drive by clean up [here's the TODO](https://github.com/CenterForOpenScience/osf.io/pull/9593/files#diff-b427522b7934e79065d8524342c6f63f34c40f3a1ff2712a36c05466b14639adL413)

2021-01-07 15:33 UTC, Johnetordoff commented on osf_tests/factories.py
> -        with patch('osf.models.AbstractNode.update_search'):
This isn't necessary anymore because the search is configured differently then it was when this was written.

2021-02-01 19:00 UTC, jwalz requested changes

2021-02-02 13:18 UTC, Johnetordoff commented
closed in favor of https://github.com/CenterForOpenScience/osf.io/pull/9598

2021-02-02 13:18 UTC, closed without merging