Add management command to copy contributors from projects to draft registrations
CenterForOpenScience/osf.io pull request #9632
Opened 2021-03-05 21:35 UTC by UdayVarkhedkar

## Purpose
We are modifying draft registrations to copy contributors from the branched project upon creation. This means that post-release all new draft registrations will have contributors from the branched project. Pre-release draft registrations will not have contributors from the branched project. This management command ensures that existing draft registrations contributor permissions are in line with what users expect after contributor management shifts to be on the draft registration. 

## Changes
- Creates a management command to copy contributors from projects to active draft registrations
- Creates a test for the management command

## QA Notes
This should be dev tested on a staging environment

## Documentation
N/A

## Side Effects
N/A

## Ticket
[JIRA Ticket](https://openscience.atlassian.net/browse/ENG-2626)

2021-03-05 21:36 UTC, UdayVarkhedkar commented
@mfraezz You may want to review this as well

2021-03-11 19:36 UTC, corbinSanders commented on osf/management/commands/project_to_draft_registration_contributor_sync.py
> +        draft_reg.copy_contributors_from(draft_reg.branched_from)
Could you put a dry run in with this?

2021-03-11 19:44 UTC, corbinSanders commented on osf_tests/test_management_commands.py
> +@pytest.mark.django_db
Solid tests!

2021-03-11 19:44 UTC, corbinSanders requested changes
Nit: having a dry run would be nice, but not **Super** necessary.

2021-03-18 14:08 UTC, corbinSanders approved these changes
LGTM! 🎊

2021-03-19 18:37 UTC, UdayVarkhedkar commented on osf/management/commands/project_to_draft_registration_contributor_sync.py
> +def retrieve_draft_registrations_to_sync():
Filter for draft registrations based solely off a node as opposed to draft node

2021-03-19 18:39 UTC, UdayVarkhedkar commented on osf/management/commands/project_to_draft_registration_contributor_sync.py
> +    active_unsynced_draft_regs = active_draft_registrations.annotate(num_contributor=Count('_contributors')).filter(num_contributor=1)
add `lte` for num_contributor; check to ensure a draft registration can't end up with no contributors

2021-03-19 18:40 UTC, UdayVarkhedkar commented on osf_tests/test_management_commands.py
> +        # Tests if the function used to retriev draft registrations to copy project contributors
typo

2021-03-23 18:14 UTC, merged