[ENG-2691] Feature/noproject email fixes
CenterForOpenScience/osf.io pull request #9650
Opened 2021-03-24 19:01 UTC by jwalz

## Purpose
Make sure initiators of a "No-Project" Draft Registration receive an email with the link to the registration.

Draft Registrations that are not associated with a Project currently have no means of discovery beyond the email link sent to contributors. Historically, contributors

## Changes
* Call the `contributor_added` signal in `DraftRegistration.create_from_node` when creating a DraftRegistration without a backing project.
* Update the `send_mail` call when notifying new contributors to pass all args as kwargs to improve hygiene
* Update the `URL_TEMPLATE` for DraftRegistrations to match the correct, updated format
* Minor fix to email text for new Draft Registration contributors
* Tests to confirm new behavior

## QA Notes
New tests verify that email is sent to the initiator iff the draft node is created without a `branched_from` node.

QA/Product should verify email text

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket
https://openscience.atlassian.net/browse/ENG-2691

2021-03-24 19:26 UTC, UdayVarkhedkar requested changes
Looks good outside of what should be that quick change to the `url` property on the draftregistration class!

2021-03-24 19:27 UTC, jwalz commented on osf/models/registrations.py
> +    URL_TEMPLATE = settings.DOMAIN + 'registries/drafts/{draft_id}'
Good catch! I'm excited to see how many tests this broken format call breaks.

2021-03-24 19:30 UTC, UdayVarkhedkar approved these changes

2021-03-25 15:53 UTC, corbinSanders commented on osf/models/registrations.py
> +    URL_TEMPLATE = settings.DOMAIN + 'registries/drafts/{draft_id}'
How many tests did it end up breaking?

2021-03-25 16:03 UTC, jwalz commented on osf/models/registrations.py
> +    URL_TEMPLATE = settings.DOMAIN + 'registries/drafts/{draft_id}'
none due to the .format call, somehow; one due to explicitly testing for the old url format

2021-03-25 16:05 UTC, merged