[Hotfix][ENG-3205] Add Character Lab Long and Short Form Registration Schemas
CenterForOpenScience/osf.io pull request #9754
Opened 2021-09-02 13:36 UTC by Johnetordoff

## Purpose

Give CL two new schemas!

## Changes

- adds two new schemas for CL

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-3205

2021-09-08 00:33 UTC, jwalz requested changes
There's a discrepancy between the CSV and the actual schema block types. They use "multiple-input-option" instead of "multi-select-input". I flagged all of the spots where we got caught by that.

Other than that, it sounds like this should now be merged to Develop instead of Hotfixed, in which case you could also incorporate some of the readability improvements from https://github.com/CenterForOpenScience/osf.io/pull/9747 (e.g. not including empty help_text/example_text)

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
should be "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-short-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 00:33 UTC, jwalz commented on website/project/metadata/character-lab-long-form-registration.json
> +		"block_type": "multiple-input-option",
-> "multi-select-input"

2021-09-08 15:14 UTC, jwalz requested changes
still using the unsupported `multiple-select-option` value for `block_type` instead of `multi-select-input`, also, trailing commas are breaking json validation. I fixed the spreadsheet values with the wrong `block_type`, if that helps.

2021-09-08 15:15 UTC, jwalz commented
Oh, and these files need to be added to the list in website/project/metadata/schemas.py

2021-09-15 20:35 UTC, adlius commented on website/project/metadata/character-lab-long-form-registration.json
> +		"display_text": "Is this a pilot?"
there should be a `single-select-input` block after this block.

2021-09-15 20:36 UTC, adlius requested changes

2021-09-15 20:36 UTC, adlius commented on website/project/metadata/character-lab-long-form-registration.json
> +		"display_text": "Is this a pilot?"
There should be a `single-select-input` block after this block.

2021-09-22 20:33 UTC, jwalz commented
Closed in favor of https://github.com/CenterForOpenScience/osf.io/pull/9767

2021-09-22 20:33 UTC, closed without merging