move blocked email domains to post-migrate signal
CenterForOpenScience/osf.io pull request #9958
Opened 2022-06-18 21:01 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

## Documentation

## Side Effects

## Ticket

2022-06-27 18:48 UTC, jwalz reviewed
Double check with Abram and Eric about default allow_list for emails (pull domains for institutions?)

2022-07-12 16:45 UTC, cslzchen requested changes
As mentioned, need to revert the name from `DENY_EMAIL_DOMAINS` to `BLACKLISTED_DOMAINS`. The rest looks good! 🎆 

And just re-surface @jwalz 's previous review, we need to `create_or_update` instead of using `bulk_create` since [1.11](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create) doesn't have `ignore_conflicts` yet.

In addition, I am not sure if should use `bulk_create` with `ignore_conflicts` after the upgrade since we are updating the list after initial creation. May want to take a look at performance concerns if `bulk_create` is used to add only a few new items to a long list.

2022-07-12 17:34 UTC, jwalz commented on website/settings/defaults.py
> +DENY_EMAIL_DOMAINS = [
Lame but makes sense

2022-07-13 17:02 UTC, cslzchen approved these changes
Looks great! I will take care of the conflicts fix + doing some local test for the iterative domain update/create before merging. 🌟

2022-07-13 20:05 UTC, merged